name: travel_hour
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.1.3+18

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  
  animated_bottom_navigation_bar: ^1.2.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.7.1
  cupertino_icons: ^1.0.5
  dots_indicator: ^3.0.0
  easy_localization: ^3.0.2
  firebase_analytics: ^10.4.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  firebase_storage: ^11.2.1
  firebase_in_app_messaging: ^0.7.3+1
  flare_flutter: ^3.0.2
  flutter_html: ^3.0.0-beta.1
  flutter_polyline_points: ^1.0.0
  geo: ^0.3.0
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.8
  google_sign_in: ^6.1.2
  html_unescape: ^2.0.0
  http: ^0.13.6
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  package_info: ^2.0.2
  provider: ^6.0.3
  share: ^2.0.4
  shared_preferences: ^2.1.1
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.11
  the_apple_sign_in: ^1.1.1
  fluttertoast: ^8.2.1
  flutter_facebook_auth: ^5.0.11
  flutter_web_browser: ^0.17.1
  google_mobile_ads: ^3.0.0
  # facebook_audience_network: ^1.0.1
  pod_player: ^0.1.4
  app_settings: ^4.2.0
  csslib: 0.17.2
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
  another_carousel_pro:
    git:
      url: https://github.com/iamnabink/another_carousel_pro
      ref: 6bd1b57


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"






flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/flr/
    - assets/translations/

    

  fonts:

    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800


    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900


    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
