// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCROa8LxAHmRY2k1lahWj5ESFvJjzRs_v4',
    appId: '1:104306170554:web:4df696d3e2be3ec7bcc083',
    messagingSenderId: '104306170554',
    projectId: 'final-project-347cb',
    authDomain: 'final-project-347cb.firebaseapp.com',
    storageBucket: 'final-project-347cb.appspot.com',
    measurementId: 'G-YW25EH7LRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC9sTN1yzxVfPnRvPCPIUUcjKSbqM5fW0',
    appId: '1:104306170554:android:232699ff9c80fdeebcc083',
    messagingSenderId: '104306170554',
    projectId: 'final-project-347cb',
    storageBucket: 'final-project-347cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtfNAqDnnP8EtC4dt9BAVZvdWAM_dyOnU',
    appId: '1:104306170554:ios:b0b68ea92358b298bcc083',
    messagingSenderId: '104306170554',
    projectId: 'final-project-347cb',
    storageBucket: 'final-project-347cb.appspot.com',
    androidClientId: '104306170554-28kmjn06mj69mihd8ups4p6r5594g35l.apps.googleusercontent.com',
    iosClientId: '104306170554-i2no7j7qog57lrrekbp13dtgil71sbp4.apps.googleusercontent.com',
    iosBundleId: 'com.mrblab.travelhourapp',
  );
}
